FROM maven:3.8.4-openjdk-17-slim

COPY zero/Module#04 /usr/src/app

WORKDIR /usr/src/app

RUN mvn clean install -DskipTests -X

EXPOSE 8080

CMD ["java", "-jar", "web-app/target/web-app-1.0.0.war"]

HEALTHCHECK --interval=30s --timeout=10s CMD curl --fail http://localhost:8080/health || exit 1
