name: Deploy to Tomcat
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build project
        run: mvn clean package
      
      - name: Install Tomcat
        run: sudo apt-get update && sudo apt-get install tomcat7

      - name: Install Tomcat
        run: find . -name gift.war

      - name: Copy WAR file
        run: |
        sudo mkdir -p /usr/share/tomcat7/webapps/
        sudo cp api/target/*.war /usr/share/tomcat7/webapps/
      
      - name: Start Tomcat
        run: sudo service tomcat7 start
