name: Java CI with Maven(Gift-shop)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Ip
        run: ip address

      - name: find file
        run: find . -name api-1.0.0.jar
