name: Run REST-API with Maven(Gift-shop)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Ip
        run: ip address

      - name: find Jar
        run: find . -name api-0.0.1-SNAPSHOT.jar

      - name: run java
        run: java -jar ./api/target/api-0.0.1-SNAPSHOT.jar