name: Build and Test Java 17

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 with setup-java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Main
        run: cd zero

      - name: list
        run: ls -la

      - name: Module#04
        run: cd Module#04

      - name: list
        run: ls -la

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml

      - name: find file
        run: find . -name web-app-1.0.0.jar
