name: Java 1.8 CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and run Java project
        uses: apache/maven@v3.8.3
        with:
          java-home: ${{ env.JAVA_HOME }}
          goals: 'clean install'

      - name: package file
        run: mvn -B package --file pom.xml

      - name: check path
        run: ls -la && pwd

      - name: find Jar
        run: find . -name api-0.0.1-SNAPSHOT.jar

      - name: run java
        run: java -jar ./api/target/api-0.0.1-SNAPSHOT.jar
