name: Java CI with Maven(Gift-shop)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests -Dmaven.compiler.source=11 -Dmaven.compiler.target=11

      - name: Ip
        run: ip address

      - name: find file
        run: find . -name api-0.0.1-SNAPSHOT.jar