name: REST-API Spring Java (Gradle)

on:
  push:
    branches: [ "module#2" ]
  pull_request:
    branches: [ "module#2" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}


    - name: chmod with gradlew
      run: chmod +x gradlew

    - name: View directory
      run: pwd && ls -ltr

    - name: Assemble App module and test with Gradle
      run:  build clean test

    - name: Run Api main
      run:  ./gradlew :app:run

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publishToMavenLocal

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
