name: Java install openjdk-11-jdk

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: sudo apt-get update
        run: sudo apt-get update

      - name: package file
        run: mvn clean package -DskipTests -Dmaven.compiler.source=11 -Dmaven.compiler.target=11

      - name: check path
        run: ls -la && pwd

      - name: find Tomcat
        run: find . -name gift.war

      - name: run java
        run: java -jar ./api/target/api-0.0.1-SNAPSHOT.jar
