name: Run openjdk-11-jdk

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: sudo apt-get update
        run: sudo apt-get update

      - name: sudo apt-get install openjdk-8-jdk
        run: sudo apt-get install openjdk-8-jdk -y

      - name: openjdk-8-jre
        run: sudo apt-get install openjdk-8-jre -y

      - name: java -version
        run: mvn -B package --file pom.xml -X

      - name: gift.war
        run: ls -la && ip address


      - name: find Jar
        run: find . -name api-0.0.1-SNAPSHOT.jar

      - name: run java
        run: java -jar ./api/target/api-0.0.1-SNAPSHOT.jar
