name: Run openjdk-11-jdk

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: package file
        run: mvn -B package --file pom.xml

      - name: check path
        run: ls -la && pwd

      - name: find Jar
        run: find . -name api-0.0.1-SNAPSHOT.jar

      - name: run java
        run: java -jar ./api/target/api-0.0.1-SNAPSHOT.jar
