name: Java install openjdk-17-jdk and Run Jar

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 with setup-java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml

      - name: find file
        run: find . -name web-app-1.0.0.jar

#      - name: run java
#        run: java -jar ./web-app/target/web-app-1.0.0.jar
